### ISSUE TITLE
Main Menu font glitch - tiny underlines under menu options right after changing selection

### ISSUE THREAD

**Issue by lincolnfrog** [luqui/ichor#2]
When you press down/up arrows on main menu to change the menu option, small partial underlines appear under the main menu items. They flicker for a bit and then disappear when you don't change the selection for a few seconds.

Reported on my mid 2009 macbook pro. Will try on another machine soon.

I took a screenshot for you but taking a screenshot on Mac doesn't seem to work for Ichor...?

**Comment by luqui** [comment]
Oh I'm reproing this actually.  i guess my eyes aren't good enough when not wearing glasses to catch them.  Thanks!
